version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
   configuration: docs/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

build:
  commands:
    - make -C docs/ html
