sudo: required
dist: xenial

services:
  - docker

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - cd src
  - python -m vfb_connect.owl.test.query_tools_test
  - python -m vfb_connect.test.cross_server_tools_test
  - python -m vfb_connect.neo.test.neo_tools_tests
