name: Query Roller
on: [push, release]

jobs:
  notebooks:
    name: "Roll Queries"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          
      - name: Run Query Roller
        run: |
          cd src
          python -c '
          vfb_query_builder.query_roller.TermInfoExport()
          '
      
      - name: Commit any changes
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/vfb_connect/resources/VFB_TermInfo_queries.json
          git commit -m "Queries updated"
          git push
