name: Jupyter Notebook checks
on: [push, release]

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .
          python -m pip install -r .github/workflows/requirements.txt

      - name: Execute the tutorial notebooks
        run: |
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=900 docs/source/tutorials/*.ipynb

      - name: Execute the snippet notebooks
        run: |
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=900 snippets/*.ipynb


      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/tutorials

    
