name: VFB_connect tests
on: [push, release]

jobs:
  notebooks:
    name: "Test VFB_connect"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
          
      - name: Cache VFB lookup tables
        uses: actions/cache@v3
        with:
          path: |
            src/vfb_connect/lookup_cache.pkl
            ~/.cache/vfb_connect/
          key: vfb-lookup-cache-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            vfb-lookup-cache-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -r .github/workflows/requirements.txt
          
      - name: Test essential functionality (LC_12 fix verification)
        timeout-minutes: 5
        run: |
          cd src
          python -c "
          import sys, time
          from vfb_connect import vfb
          print('🔧 Testing main fix: LC_12 ambiguous match resolution...')
          
          # Test the main fix - the core issue we solved
          test_cases = ['LC_12', 'LC12', 'LC 12', ' LC12 ']
          all_passed = True
          
          for case in test_cases:
              try:
                  result = vfb.lookup_id(case, verbose=False)
                  expected = 'FBbt_00100484'
                  if result == expected:
                      print(f'  ✅ {case:<8} -> {result}')
                  else:
                      print(f'  ❌ {case:<8} -> {result} (expected {expected})')
                      all_passed = False
              except Exception as e:
                  print(f'  💥 {case:<8} -> Error: {e}')
                  all_passed = False
          
          if all_passed:
              print('🎉 All LC_12 variations working correctly!')
              print('🎉 Main ambiguous match fix verified!')
          else:
              print('❌ LC_12 fix verification failed!')
              sys.exit(1)
          "
          
      - name: Run essential tests (core functionality)
        timeout-minutes: 8
        run: |
          cd src
          echo "Running core lookup tests..."
          python -m unittest \
            vfb_connect.schema.test.vfb_term_test.VfbTermTest.test_lookups \
            vfb_connect.schema.test.vfb_term_test.VfbTermTest.test_lookups_matching \
            vfb_connect.schema.test.vfb_term_test.VfbTermTest.test_lookup_names \
            vfb_connect.test.cross_server_tools_test.VfbConnectTest.test_lookup_id \
            -v
