name: VFB_connect tests
on: [push, release]

jobs:
  notebooks:
    name: "Test VFB_connect"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          
      - name: Run the query_tools tests
        run: |
          cd src
          python -m vfb_connect.owl.test.query_tools_test
          
      - name: Run the cross_server_tools tests
        run: |
          cd src
          python -m vfb_connect.test.cross_server_tools_test
          
      - name: Run the neo_tools tests
        run: |
          cd src
          python -m vfb_connect.neo.test.neo_tools_tests
