name: Jupyter Notebook checks
on: [push, release]

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .
          python -m pip install -r .github/workflows/requirements.txt

      - name: Execute tutorial notebooks (serial execution)
        run: |
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 docs/source/tutorials/overview.ipynb
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 docs/source/tutorials/vfb_terms.ipynb
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 docs/source/tutorials/discovery.ipynb
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 docs/source/tutorials/vfb_neurons.ipynb
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1200 docs/source/tutorials/connectomics.ipynb
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 docs/source/tutorials/vfb_datasets.ipynb

      - name: Execute snippet notebooks (serial execution)
        run: |
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 snippets/VFB_connect_Quick_Guide.ipynb


      - uses: actions/upload-artifact@v4
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/tutorials

    
